name: PHP Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Validasi ini hanya diperlukan jika Anda menggunakan Composer.
    # Jika tidak diperlukan, silakan hapus atau komentari bagian ini.
    # - name: Validate composer.json and composer.lock
    #   run: composer validate --strict

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./sistem-pinjam # Ubah sesuai struktur proyek
        push: true
        tags: almahfuzhrohman/sistem-pinjam:latest
